"""Generate docs/adr/INDEX.md from the records' frontmatter.

uv run python docs/adr/_scripts/gen_adr_index.py            # rewrite the index
uv run python docs/adr/_scripts/gen_adr_index.py --check    # exit 1 when the index on disk is stale
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent  # docs/adr
INDEX = ROOT / "INDEX.md"
_LINK = re.compile(r"\[\[([^\]|#\\]+)(?:#[^\]|\\]+)?\\?(?:\|([^\]]+))?\]\]")


def read(path: Path) -> dict[str, str]:
    text = path.read_text()
    head = text[4:].partition("\n---\n")[0] if text.startswith("---\n") else ""
    fm: dict[str, str] = {"deps": ""}
    key = None
    deps: list[str] = []
    for line in head.splitlines():
        if line.startswith("  - ") and key == "depends_on":
            m = _LINK.search(line)
            deps.append(
                (m.group(2) or m.group(1)) if m else line[4:].strip().strip('"')
            )
        elif ":" in line:
            key, _, value = line.partition(":")
            fm[key.strip()] = value.strip().strip('"')
    fm["deps"] = ", ".join(deps) if deps else "none"
    title = re.search(r"^# (.+)$", text, re.M)
    fm["title"] = title.group(1) if title else path.stem
    return fm


def render() -> str:
    records = sorted(ROOT.glob("*/ADR-*.md"), key=lambda p: p.stem)
    rows = [
        "# Corpus index: generated by scripts/gen_adr_index.py, do not hand-edit",
        "",
    ]
    rows.append("| record | topic | status | liveness | depends on |")
    rows.append("|---|---|---|---|---|")
    by_topic: list[tuple[str, str]] = []
    for p in records:
        fm = read(p)
        rel = p.relative_to(ROOT)
        rows.append(
            f"| [{fm['adr']}]({rel}) | {p.parent.name} | {fm['status']} | {fm['liveness']} | {fm['deps']} |"
        )
        by_topic.append((p.parent.name, fm["title"]))
    rows += ["", "## By topic", ""]
    for topic, title in by_topic:
        rows.append(f"- **{topic}**, {title}")
    rows.append("")
    return "\n".join(rows)


def main(argv: list[str]) -> int:
    text = render()
    if "--check" in argv:
        current = INDEX.read_text() if INDEX.exists() else ""
        if current != text:
            print(
                "docs/adr/INDEX.md is stale; run: uv run python scripts/gen_adr_index.py",
                file=sys.stderr,
            )
            return 1
        return 0
    INDEX.write_text(text)
    print(f"wrote {INDEX.relative_to(ROOT.parent.parent)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
